name: Publish to NPM

# TRIGGERS:
# 1. GitHub Release created (manual via GitHub UI)
# 2. Version tag pushed (automated via `npm run release`)
#
# The release scripts do: npm version patch → git push --follow-tags
# This pushes a v* tag, which triggers this workflow automatically.
# No need to manually create a GitHub Release.
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

# Ensure only one publish runs at a time
concurrency:
  group: publish
  cancel-in-progress: false

# Top-level permissions for provenance (SLSA Build L3)
# id-token: write is REQUIRED for npm --provenance via OIDC
permissions:
  contents: read
  id-token: write

jobs:
  # Prevent duplicate runs: if both release + tag fire, skip the tag-triggered run
  check-duplicate:
    name: Deduplicate Triggers
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check if this is a duplicate run
        id: check
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # Tag push: check if a GitHub Release already exists for this tag
            # If it does, the release event will handle it — skip this run
            TAG="${GITHUB_REF#refs/tags/}"
            echo "Tag push detected: $TAG"
            echo "Checking if a GitHub Release exists for this tag..."
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN || '' }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG" 2>/dev/null || echo "000")
            if [ "$STATUS" = "200" ]; then
              echo "GitHub Release found for $TAG — skipping tag-push run (release event will handle it)"
              echo "should_run=false" >> $GITHUB_OUTPUT
            else
              echo "No GitHub Release for $TAG — proceeding with tag-push publish"
              echo "should_run=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "Release event — proceeding"
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  validate:
    name: Pre-publish Validation
    runs-on: ubuntu-latest
    needs: check-duplicate
    if: needs.check-duplicate.outputs.should_run == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Flatten Figma Make src/ structure
        run: bash scripts/flatten-src.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            echo "WARNING: No lockfile. Using npm install."
            npm install
          fi

      - name: Strip Figma Make versioned imports
        run: node scripts/strip-versioned-imports.mjs

      - name: TypeScript type check
        run: npm run typecheck

      - name: Run tests
        run: npm test

      - name: Check circular dependencies
        run: npm run check:circular

  version-check:
    name: Version Consistency Check (G6)
    runs-on: ubuntu-latest
    needs: check-duplicate
    if: needs.check-duplicate.outputs.should_run == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Flatten Figma Make src/ structure
        run: bash scripts/flatten-src.sh

      - name: Validate version matches release tag
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          # Extract tag from either release event or tag push
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG_VERSION="${{ github.event.release.tag_name }}"
          else
            TAG_VERSION="${GITHUB_REF#refs/tags/}"
          fi
          TAG_VERSION="${TAG_VERSION#v}"
          echo "package.json version: $PKG_VERSION"
          echo "Git tag version:      $TAG_VERSION"
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "ERROR: Version mismatch!"
            echo "package.json says $PKG_VERSION but tag says $TAG_VERSION"
            echo ""
            echo "Fix: Use the release scripts which keep everything in sync:"
            echo "  npm run release        # for patch (0.0.x)"
            echo "  npm run release:minor  # for minor (0.x.0)"
            echo "  npm run release:major  # for major (x.0.0)"
            exit 1
          fi
          echo "Version $PKG_VERSION matches tag. Proceeding."

  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: [validate, version-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Flatten Figma Make src/ structure
        run: bash scripts/flatten-src.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            echo "WARNING: No lockfile. Using npm install."
            npm install
          fi

      - name: Strip Figma Make versioned imports
        run: node scripts/strip-versioned-imports.mjs

      - name: Build Library (ESM with preserveModules)
        run: npm run build:lib

      - name: Verify build output
        run: |
          if [ ! -d "dist-lib" ]; then
            echo "ERROR: dist-lib directory was not created"
            exit 1
          fi
          echo "=== Build Output ==="
          ls -la dist-lib/
          echo ""
          echo "Module count:"
          find dist-lib -name '*.js' | wc -l
          echo ""
          echo "Total size:"
          du -sh dist-lib/

      - name: Run boundary check
        run: npm run check:boundary

      - name: Run exports validation
        run: npm run check:exports

      - name: Verify sub-path exports
        run: |
          echo "=== Checking sub-path entry points ==="
          ENTRIES=(
            "dist-lib/index.js"
            "dist-lib/components/ui/index.js"
            "dist-lib/components/patterns/index.js"
            "dist-lib/components/advanced/index.js"
            "dist-lib/components/widgets/index.js"
            "dist-lib/components/providers/index.js"
            "dist-lib/hooks/index.js"
            "dist-lib/lib/index.js"
          )
          for entry in "${ENTRIES[@]}"; do
            if [ ! -f "$entry" ]; then
              echo "MISSING: $entry"
              exit 1
            fi
            echo "  OK: $entry"
          done

      - name: Verify npm pack contents
        run: |
          echo "=== Package Contents Preview ==="
          npm pack --dry-run 2>&1 | head -100
          echo ""
          TARBALL=$(npm pack 2>/dev/null)
          SIZE=$(du -sh "$TARBALL" | cut -f1)
          FILES=$(tar -tzf "$TARBALL" | wc -l)
          echo "Package: $TARBALL"
          echo "Size: $SIZE"
          echo "Files: $FILES"
          echo ""
          echo "=== Checking required files in tarball ==="
          REQUIRED_FILES=(
            "package/dist-lib/index.js"
            "package/dist-lib/index.d.ts"
            "package/styles/theme.css"
            "package/llms.txt"
            "package/LICENSE"
            "package/README.md"
            "package/CHANGELOG.md"
          )
          for req in "${REQUIRED_FILES[@]}"; do
            if tar -tzf "$TARBALL" | grep -q "^${req}$"; then
              echo "  OK: $req"
            else
              echo "  MISSING: $req"
              exit 1
            fi
          done
          rm -f "$TARBALL"
          echo ""
          echo "All required files present in tarball."

      # --ignore-scripts prevents prepublishOnly from re-running
      # the full validate pipeline (CI already ran it above)
      - name: Publish to NPM
        run: npm publish --access public --provenance --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post-publish summary
        if: success()
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "========================================="
          echo "  Published @biomahd-creator/financio-design-system@$PKG_VERSION"
          echo "========================================="
          echo ""
          echo "Install:"
          echo "  npm install @biomahd-creator/financio-design-system@$PKG_VERSION"
          echo ""
          echo "Import options:"
          echo '  import { Button } from "@biomahd-creator/financio-design-system";'
          echo '  import { Button } from "@biomahd-creator/financio-design-system/ui";'
          echo '  import { Button } from "@biomahd-creator/financio-design-system/ui/button";'
          echo ""
          echo "AI/LLM: llms.txt included in package"
          echo "Security: Published with --provenance (SLSA Build L3)"
          echo "License: MIT (LICENSE file included)"