name: Validate Design System

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# Reusable install command:
# - Uses `npm ci` if package-lock.json exists (deterministic, fast)
# - Falls back to `npm install` if no lockfile (first clone, new contributors)
# After first run, commit the generated package-lock.json for reproducible builds.

jobs:
  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Lockfile found — using npm ci (deterministic)"
            npm ci
          else
            echo "WARNING: No package-lock.json found. Using npm install."
            echo "Run 'npm install' locally and commit the lockfile for reproducible builds."
            npm install
          fi

      - name: Run TypeScript type check (tsc --noEmit)
        run: npm run typecheck

  test:
    name: Unit & Component Tests (G2)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            echo "WARNING: No lockfile. Using npm install."
            npm install
          fi

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 14

  build-lib:
    name: Library Build + Tree-Shaking Validation (G3)
    runs-on: ubuntu-latest
    needs: [typecheck, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi

      - name: Build library (ESM with preserveModules)
        run: npm run build:lib

      - name: Verify dist-lib output exists
        run: |
          if [ ! -d "dist-lib" ]; then
            echo "ERROR: dist-lib directory was not created"
            exit 1
          fi
          echo "dist-lib contents:"
          ls -la dist-lib/
          echo ""
          echo "Build output size:"
          du -sh dist-lib/
          echo ""
          echo "Module count:"
          find dist-lib -name '*.js' | wc -l

      - name: Verify sub-path entry points exist
        run: |
          echo "=== Checking sub-path entry points (G3) ==="
          ENTRIES=(
            "dist-lib/index.js"
            "dist-lib/components/ui/index.js"
            "dist-lib/components/patterns/index.js"
            "dist-lib/components/advanced/index.js"
            "dist-lib/components/widgets/index.js"
            "dist-lib/components/providers/index.js"
            "dist-lib/hooks/index.js"
            "dist-lib/lib/index.js"
          )
          MISSING=0
          for entry in "${ENTRIES[@]}"; do
            if [ -f "$entry" ]; then
              echo "  OK: $entry"
            else
              echo "  MISSING: $entry"
              MISSING=$((MISSING + 1))
            fi
          done
          if [ $MISSING -gt 0 ]; then
            echo "ERROR: $MISSING entry point(s) missing"
            exit 1
          fi
          echo "All entry points present."

  boundary-check:
    name: Library Boundary & Exports Check (G1)
    runs-on: ubuntu-latest
    needs: build-lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi

      - name: Build library for boundary check
        run: npm run build:lib

      - name: Run boundary check
        run: npm run check:boundary

      - name: Run exports validation
        run: npm run check:exports

      - name: Verify package metadata files
        run: |
          echo "=== Required metadata files ==="
          FILES=("LICENSE" "README.md" "CHANGELOG.md" "llms.txt" "styles/theme.css")
          for f in "${FILES[@]}"; do
            if [ -f "$f" ]; then
              echo "  OK: $f"
            else
              echo "  MISSING: $f"
              exit 1
            fi
          done

  circular-deps:
    name: Circular Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi

      - name: Check for circular dependencies (madge)
        run: npm run check:circular

  package-dry-run:
    name: Package Dry Run
    runs-on: ubuntu-latest
    needs: build-lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi

      - name: Build library
        run: npm run build:lib

      - name: Dry-run npm pack
        run: |
          echo "=== npm pack --dry-run ==="
          npm pack --dry-run 2>&1
          echo ""
          TARBALL=$(npm pack 2>/dev/null)
          SIZE=$(du -sh "$TARBALL" | cut -f1)
          FILES=$(tar -tzf "$TARBALL" | wc -l)
          echo "Tarball: $TARBALL"
          echo "Size: $SIZE"
          echo "Files in package: $FILES"
          echo ""
          # Warn if package is over 5MB (potential bloat)
          SIZE_BYTES=$(stat --format=%s "$TARBALL" 2>/dev/null || stat -f%z "$TARBALL" 2>/dev/null)
          if [ "$SIZE_BYTES" -gt 5242880 ]; then
            echo "WARNING: Package is over 5MB ($SIZE). Consider auditing bundle size (H15)."
          else
            echo "Package size OK ($SIZE)"
          fi
          rm -f "$TARBALL"

  validate-summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [typecheck, test, build-lib, boundary-check, circular-deps, package-dry-run]
    if: always()
    steps:
      - name: Check results
        run: |
          echo "========================================="
          echo "  Validation Summary (v0.2.2)"
          echo "========================================="
          echo "TypeScript:       ${{ needs.typecheck.result }}"
          echo "Tests (G2):       ${{ needs.test.result }}"
          echo "Library Build:    ${{ needs.build-lib.result }}"
          echo "Boundary (G1):    ${{ needs.boundary-check.result }}"
          echo "Circular Deps:    ${{ needs.circular-deps.result }}"
          echo "Package Dry Run:  ${{ needs.package-dry-run.result }}"
          echo "========================================="
          if [ "${{ needs.typecheck.result }}" != "success" ] || \
             [ "${{ needs.test.result }}" != "success" ] || \
             [ "${{ needs.build-lib.result }}" != "success" ] || \
             [ "${{ needs.boundary-check.result }}" != "success" ] || \
             [ "${{ needs.circular-deps.result }}" != "success" ] || \
             [ "${{ needs.package-dry-run.result }}" != "success" ]; then
            echo "One or more validation steps failed!"
            exit 1
          fi
          echo "All validations passed!"