/**
 * Ambient module declarations for Figma Make versioned imports.
 *
 * Figma Make pins dependency versions using the `package@version` import syntax.
 * TypeScript cannot resolve these natively, so we re-export the installed
 * (unversioned) package types here.
 *
 * Also includes declarations for optional/dynamic-import-only packages
 * that are not installed locally but are externalized at build time.
 *
 * @see vite.config.lib.ts — isExternal() handles these at build time
 */

// ─── Data URI imports (generated by strip-versioned-imports.mjs) ────
// When figma:asset/* references are replaced with inline data URIs,
// TypeScript needs this declaration to resolve the import.
declare module "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" {
  const src: string;
  export default src;
}

// ─── Radix UI Primitives ────────────────────────────────────────────
declare module "@radix-ui/react-accordion@1.2.3" {
  export * from "@radix-ui/react-accordion";
}
declare module "@radix-ui/react-alert-dialog@1.1.6" {
  export * from "@radix-ui/react-alert-dialog";
}
declare module "@radix-ui/react-aspect-ratio@1.1.2" {
  export * from "@radix-ui/react-aspect-ratio";
}
declare module "@radix-ui/react-avatar@1.1.3" {
  export * from "@radix-ui/react-avatar";
}
declare module "@radix-ui/react-checkbox@1.1.4" {
  export * from "@radix-ui/react-checkbox";
}
declare module "@radix-ui/react-collapsible@1.1.3" {
  export * from "@radix-ui/react-collapsible";
}
declare module "@radix-ui/react-context-menu@2.2.6" {
  export * from "@radix-ui/react-context-menu";
}
declare module "@radix-ui/react-dialog@1.1.6" {
  export * from "@radix-ui/react-dialog";
}
declare module "@radix-ui/react-dropdown-menu@2.1.6" {
  export * from "@radix-ui/react-dropdown-menu";
}
declare module "@radix-ui/react-hover-card@1.1.6" {
  export * from "@radix-ui/react-hover-card";
}
declare module "@radix-ui/react-label@2.1.2" {
  export * from "@radix-ui/react-label";
}
declare module "@radix-ui/react-menubar@1.1.6" {
  export * from "@radix-ui/react-menubar";
}
declare module "@radix-ui/react-navigation-menu@1.2.5" {
  export * from "@radix-ui/react-navigation-menu";
}
declare module "@radix-ui/react-popover@1.1.6" {
  export * from "@radix-ui/react-popover";
}
declare module "@radix-ui/react-progress@1.1.2" {
  export * from "@radix-ui/react-progress";
}
declare module "@radix-ui/react-radio-group@1.2.3" {
  export * from "@radix-ui/react-radio-group";
}
declare module "@radix-ui/react-scroll-area@1.2.3" {
  export * from "@radix-ui/react-scroll-area";
}
declare module "@radix-ui/react-select@2.1.6" {
  export * from "@radix-ui/react-select";
}
declare module "@radix-ui/react-separator@1.1.2" {
  export * from "@radix-ui/react-separator";
}
declare module "@radix-ui/react-slider@1.2.3" {
  export * from "@radix-ui/react-slider";
}
declare module "@radix-ui/react-slot@1.1.2" {
  export * from "@radix-ui/react-slot";
}
declare module "@radix-ui/react-switch@1.1.3" {
  export * from "@radix-ui/react-switch";
}
declare module "@radix-ui/react-tabs@1.1.3" {
  export * from "@radix-ui/react-tabs";
}
declare module "@radix-ui/react-toggle@1.1.2" {
  export * from "@radix-ui/react-toggle";
}
declare module "@radix-ui/react-toggle-group@1.1.2" {
  export * from "@radix-ui/react-toggle-group";
}
declare module "@radix-ui/react-tooltip@1.1.8" {
  export * from "@radix-ui/react-tooltip";
}

// ─── UI Libraries ───────────────────────────────────────────────────
declare module "class-variance-authority@0.7.1" {
  export * from "class-variance-authority";
}
declare module "cmdk@1.1.1" {
  export * from "cmdk";
}
declare module "embla-carousel-react@8.6.0" {
  export * from "embla-carousel-react";
  export { default } from "embla-carousel-react";
}
declare module "input-otp@1.4.2" {
  export * from "input-otp";
}
declare module "lucide-react@0.487.0" {
  export * from "lucide-react";
}
declare module "react-day-picker@8.10.1" {
  export * from "react-day-picker";
}
declare module "react-hook-form@7.55.0" {
  export * from "react-hook-form";
}
declare module "react-resizable-panels@2.1.7" {
  export * from "react-resizable-panels";
}
declare module "sonner@2.0.3" {
  export * from "sonner";
}
declare module "vaul@1.1.2" {
  export * from "vaul";
}

// ─── Optional / Dynamic-import packages (externalized, not installed locally) ─
// These modules are available at runtime in Figma Make or loaded dynamically.
// Minimal type stubs allow tsc to pass without installing them.

declare module "xlsx" {
  export const utils: {
    json_to_sheet: (data: any[]) => any;
    book_new: () => any;
    book_append_sheet: (wb: any, ws: any, name?: string) => void;
  };
  export function writeFile(wb: any, filename: string): void;
  export function write(wb: any, opts: any): any;
}

declare module "driver.js" {
  export function driver(config?: any): {
    highlight: (step: any) => void;
    drive: (steps?: any) => void;
    destroy: () => void;
    moveNext: () => void;
    movePrevious: () => void;
    isActive: () => boolean;
  };
}

declare module "driver.js/dist/driver.css" {
  const content: string;
  export default content;
}

declare module "@hookform/resolvers/zod" {
  export function zodResolver(schema: any): any;
}

// ─── Packages used by library but not in dependencies ───────────────
// These are available in the Figma Make runtime. Minimal stubs for tsc.

declare module "@tanstack/react-table" {
  export type ColumnDef<TData = unknown, TValue = unknown> = any;
  export type ColumnFiltersState = any[];
  export type SortingState = any[];
  export type VisibilityState = Record<string, boolean>;
  export type Table<TData = unknown> = any;
  export type Row<TData = unknown> = any;
  export type Column<TData = unknown, TValue = unknown> = any;
  export function flexRender(component: any, props: any): any;
  export function getCoreRowModel(): any;
  export function getFilteredRowModel(): any;
  export function getPaginationRowModel(): any;
  export function getSortedRowModel(): any;
  export function useReactTable(options: any): any;
}

declare module "react-dnd" {
  export function DndProvider(props: any): any;
  export function useDrag(spec: any): any[];
  export function useDrop(spec: any): any[];
}

declare module "react-dnd-html5-backend" {
  const HTML5Backend: any;
  export { HTML5Backend };
}

declare module "react-responsive-masonry" {
  import { ComponentType } from "react";
  const Masonry: ComponentType<any>;
  export const ResponsiveMasonry: ComponentType<any>;
  export default Masonry;
}